### PR TITLE
Doc reorg

### PR DESCRIPTION
**Pull request by josephharfouch**
Reorganized the documentation so that it is centralized and is easier to navigate. 

Although there are a lot of diff changes, the documentation just moved around, so it might be easier if you can have a look at the documentation output, and see how it looks. 

Let me know what you think of it. It is just an experiment to see if this structure is better.

### CODE REVIEW

**Comment by josephharfouch** [comment]
I am struggling with git. I did the pull and merge but did not see many changes in my directory. I noticed that when I issue sbt paradox; sbt copyDocs it is changing docs/js/app-graphiql.js as well as the generated html files. Should I add the  docs/js/app-graphiql.js to .gitignore so that you don't see changes from it?

**Comment by andrewresearch** [comment]
What’s happened is that prior to your commit, there has been another commit to the main repo that has updated the js and css files (done by me). This is common when multiple people are working on the repo. 
To ensure that you don’t merge in your older versions of these files, you need to update your local copy with the server version, so either PULL and then merge the develop branch into your branch, or rebase your branch onto the newer develop branch.
Once you’ve done that, you can go ahead and create the new docs files with the paradox; copyDocs, and then you should have a local version that is up-to-date with the server and including your changes. Your pull request will then only merge in your changes.

Hope this helps.

Re: Git, take a look at this… http://nvie.com/posts/a-successful-git-branching-model/

**Comment by josephharfouch** [comment]
1) Does it look better now after my latest commits? I am getting up to date when I do the pull from develop so I am hoping my earlier merge this morning already fixed the problem.

git branch -v; git pull  https://github.com/uts-cic/tap develop 
* doc_reorg bb8aac2 README.md should contain product brief description
  master    ddf1bf4 Merge remote-tracking branch 'upstream/master'
From https://github.com/uts-cic/tap
 * branch            develop    -> FETCH_HEAD
Already up-to-date.

2) I should have really asked this at the beginning, because I noticed there are two branches Develop and master. Am I meant to be contributing only to the development branch or are my contributions currently going to both? It looks like my earlier contributions have gone to master unless I am mistaken. I started reading the git doc, but I wanted to understand our stages of the project. Is master now meant to be only a productions stable version? 

3) Is there a way that we can exclude generated html files from going into the repository? It will be easier to detect regression if they don't clutter the diffs. 

4) Also, I am surprised I can regress the code, and git doesn't issue a conflict message? Did git issue a conflict message for you? Git is different than other software control systems, but I will feel better if it did warn of the conflict.

Once I feel more confident with git, I will update CONTRIBUTING.md to document this contribution process.  I will study the documentation you gave me.

**Comment by andrewresearch** [comment]
I've answered your questions above on Gitter. You will need to re-issue the PULL REQUEST for it to update the current one. Once this is done, I should be able to merge your changes in and all will be good.

**Pull request merged**
